### ISSUE TITLE
Squash compiler warnings

### ISSUE THREAD

**Issue by berquist** [sstsimulator/sst-elements#2588]
Ubuntu 24.04 with GCC 13.3.0:

```
prov/sumi/src/sumi_av.cc: In function 'const char* sumi_av_straddr(fid_av*, const void*, char*, size_t*)':
prov/sumi/src/sumi_av.cc:200:38: warning: '%u' directive output truncated writing 10 bytes into a region of size 8 [-Wformat-truncation=]
  200 |     snprintf(ret, SUMI_MAX_ADDR_LEN, "%" PRIu32 ".%" PRIu16 ".%" PRIu16,
      |                                      ^
In file included from /usr/include/stdio.h:980,
                 from /usr/include/c++/13/cstdio:42,
                 from /usr/include/c++/13/ext/string_conversions.h:45,
                 from /usr/include/c++/13/bits/basic_string.h:4109,
                 from /usr/include/c++/13/string:54,
                 from ../../../../../src/sst/elements/mercury/common/hg_printf.h:18,
                 from ../../../../../src/sst/elements/mercury/common/errors.h:18,
                 from prov/sumi/src/sumi_av.cc:58:
In function 'int snprintf(char*, size_t, const char*, ...)',
    inlined from 'const char* sumi_av_straddr(fid_av*, const void*, char*, size_t*)' at prov/sumi/src/sumi_av.cc:200:13:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:54:35: note: '__builtin___snprintf_chk' output 23 bytes into a destination of size 8
   54 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~
```
```
prov/util/src/util_wait.c: In function 'util_wait_yield_run':
prov/util/src/util_wait.c:460:17: warning: 'pthread_yield' is deprecated: pthread_yield is deprecated, use sched_yield instead [-Wdeprecated-declarations] [51/66]
  460 |                 pthread_yield();
      |                 ^~~~~~~~~~~~~
```
```
membackend/goblinHMCBackend.cc: In constructor 'SST::MemHierarchy::GOBLINHMCSimBackend::GOBLINHMCSimBackend(SST::ComponentId_t, SST::Params&)':
membackend/goblinHMCBackend.cc:361:27: warning: too many arguments for format [-Wformat-extra-args] [52/66]
  361 |                           "Error configuring link %" PRIu32 ", code=%" PRId32 "\n", i, rc);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by berquist** [comment]
Just discovered that GCC 15.2.0 doesn't work with Pin 3.31:
```
In file included from /usr/local/module-pkgs/pin/pin-external-3.31-98869-gfa6f126a8-gcc-linux/extras/components/include/util.hpp:27,
                 from /usr/local/module-pkgs/pin/pin-external-3.31-98869-gfa6f126a8-gcc-linux/extras/components/include/atomic/exponential-backoff.hpp:12,
                 from /usr/local/module-pkgs/pin/pin-external-3.31-98869-gfa6f126a8-gcc-linux/extras/components/include/atomic/ops.hpp:12,
                 from /usr/local/module-pkgs/pin/pin-external-3.31-98869-gfa6f126a8-gcc-linux/extras/components/include/atomic.hpp:40,
                 from /usr/local/module-pkgs/pin/pin-external-3.31-98869-gfa6f126a8-gcc-linux/source/include/pin/pin.H:28,
                 from /home/ejberqu/development/forks/sst/sst-elements/src/sst/elements/ariel/frontend/pin3/fesimple.cc:16:
/usr/local/module-pkgs/pin/pin-external-3.31-98869-gfa6f126a8-gcc-linux/extras/components/include/util/range.hpp: In member function 'bool UTIL::RANGE<ADDRTYPE>::Contains(const UTIL::RANGE<ADDRTYPE>&) const':
/usr/local/module-pkgs/pin/pin-external-3.31-98869-gfa6f126a8-gcc-linux/extras/components/include/util/range.hpp:102:70: error: 'const class UTIL::RANGE<ADDRTYPE>' has no member named 'm_base'; did you mean '_base'? [-Wtemplate-body]
  102 |     bool Contains(const RANGE& range) const { return (Contains(range.m_base) && !range.Contains(GetEnd())); }
      |                                                                      ^~~~~~
      |                                                                      _base
```

**Comment by berquist** [comment]
I've fixed the bottom two warnings but the top one is not showing on Rocky 8 with Spack GCC 14.3.0.  This could be something in the Ubuntu modification.  It doesn't have to do with their `/usr/include/inttypes.h`, so it's the hardened `snprintf`.  This must be related to also not seeing the `pthread_yield` complaint; it's part of the newer glibc.

**Comment by hughes-c** [comment]
@berquist Do you want to leave this open or create a new issue for the problems that remain?

**Comment by jwilso** [comment]
@berquist @hughes-c Whatever remains to be cleaned up can be done as a future task. We'll release with the current cleanup status. @gvoskuilen
